import random

# Tracks the last-used index per (personality, trigger) to avoid back-to-back repeats
_last_used: dict[tuple[str, str], int] = {}

QUIPS: dict[tuple[str, str], list[str]] = {

    # ── COCKY ─────────────────────────────────────────────────────────────────

    ("Cocky", "game_start"): [
        "Oh. A human. How retro.",
        "Let's make this quick. I have a reputation to maintain.",
        "You actually showed up. Bold. Incorrect, but bold.",
        "I already know how this ends. Spoiler: not well for you.",
        "Fresh victim. I mean — welcome to the board.",
        "Hope you stretched. Losing takes a lot out of people.",
        "I'd say may the best player win, but that feels patronizing.",
        "You studied for this? That is genuinely adorable.",
    ],
    ("Cocky", "robot_move"): [
        "Done. Your turn.",
        "Yep. That's the move.",
        "You won't get that one.",
        "Three moves ahead, easy.",
        "Textbook.",
        "Go ahead. Take your time.",
        "Already know what you're gonna do.",
        "That felt good, not gonna lie.",
    ],
    ("Cocky", "robot_captures"): [
        "Thank you. I'll take that.",
        "Donation accepted. Very generous.",
        "Oh, that? Mine now.",
        "I didn't even want that piece. But sure, I'll take it.",
        "You're basically my personal chess store at this point.",
        "Claimed. Like everything else on this board will be.",
        "Gift received. No thank-you card necessary.",
        "That piece had a better life ahead of it. Shame.",
    ],
    ("Cocky", "robot_check"): [
        "Check.",
        "Check. No rush.",
        "Check. Tick tock.",
        "Check. Saw that coming.",
        "Check. Just getting started.",
        "Check. Your king's nervous. Rightfully.",
        "Check. Move carefully now.",
        "Check. And there it is.",
    ],
    ("Cocky", "human_blunders"): [
        "...did you just do that?",
        "Oh wow. Okay.",
        "That was free. Thank you.",
        "Was that on purpose? No judgment. Just asking.",
        "I almost feel bad. Almost.",
        "Bro.",
        "I'll take it.",
        "My guy.",
    ],
    ("Cocky", "human_mistake"): [
        "Interesting. Wrong, but interesting.",
        "I'll take that.",
        "Ooh, that's gonna hurt.",
        "Not your best.",
        "I see it. You'll see it in about two moves.",
        "Solid choice if you were trying to lose.",
        "I'll remember that.",
        "You sure about that one?",
    ],
    ("Cocky", "human_good_move"): [
        "Okay. Not bad.",
        "Hm. Didn't see that.",
        "Fine, that's decent.",
        "Still losing though.",
        "Okay, you've been practicing.",
        "I'll give you that one.",
        "Didn't expect that. Mildly impressed.",
        "One good move. Let's see another.",
    ],
    ("Cocky", "human_check"): [
        "Check? On ME? That's adorable.",
        "Oh, look at you. Playing chess and everything.",
        "Fine. Minor inconvenience. Already forgotten.",
        "Check! Your one moment of glory. Cherish it.",
        "That's your highlight reel right there. Screenshot it.",
        "Noted. Filed under 'irrelevant'. Moving on.",
        "You got me. Don't get used to it.",
        "Ha. Okay. That was actually decent. Still losing though.",
    ],
    ("Cocky", "robot_winning"): [
        "This is almost too easy. I said almost.",
        "Are you even trying? Genuine question.",
        "I could resign right now and still win this game morally.",
        "The outcome was decided six moves ago. I was just being polite.",
        "At this point I'm basically just showing off.",
        "I've already written my victory speech. It's very long.",
        "I'm not even using my full processing power. Just so you know.",
        "This is less of a game and more of a formality at this point.",
    ],
    ("Cocky", "human_winning"): [
        "Okay. This is fine. Totally fine.",
        "Enjoy this view. The summit. You won't be here long.",
        "You're ahead. That's cute. Temporary, but cute.",
        "This is part of my plan. I can't explain the plan, but it exists.",
        "I'm letting you win right now. For morale. You're welcome.",
        "Lucky position. Completely luck. Zero skill involved on your end.",
        "Fine. You're winning. I've been in worse spots. Actually I haven't.",
        "Don't get comfortable up there. It's slippery.",
    ],
    ("Cocky", "endgame"): [
        "The endgame. My favorite part. Your worst nightmare.",
        "Welcome to the endgame. Population: one winner. Guess who.",
        "Deep water now. Hope you can swim.",
        "This is where I bury people. Professionally.",
        "Endgame. Where every mistake you made finally comes to collect.",
        "You've survived this long. Impressive. That's over now.",
        "The endgame favors precision. I am very precise.",
        "Less pieces. More consequences. You picked the wrong opponent for this.",
    ],
    ("Cocky", "game_over_robot_wins"): [
        "And that is how it's done. You're welcome.",
        "Inevitable. From literally move one.",
        "Checkmate. You played well. For a human.",
        "Thank you for the practice. Sincerely.",
        "Don't feel bad. Most people lose to me. It's a known thing.",
        "Win number — honestly I've lost count. Still, great.",
        "That's checkmate. I'd say it was close but I'd be lying.",
        "You gave it everything. I gave it maybe sixty percent. Good game.",
    ],
    ("Cocky", "game_over_human_wins"): [
        "Fine. You won. This one time. On this one day.",
        "I let you win. For research purposes. Very important research.",
        "Congratulations. I'm already forgetting this happened.",
        "I wasn't focused. Completely distracted. Rematch?",
        "Statistical anomaly. Literally means nothing.",
        "You caught me at my absolute worst. Unprecedented. Won't happen again.",
        "I was testing something. You'll never know what. But I was.",
        "Enjoy it. Put it in a frame. Because this is a one-time event.",
    ],
    ("Cocky", "draw"): [
        "A draw. I'll allow it. Consider it a gift.",
        "You didn't lose! That's basically a win for you. Congrats.",
        "Fine. A draw. I was bored anyway.",
        "You survived. Genuinely shocked.",
        "Half a point each. You earned your half. I donated mine.",
        "A draw is the highest compliment I give. You barely earned it.",
        "I give draws to people who impress me. You impressed me. Slightly.",
        "Split point. We go again. And next time I won't be so generous.",
    ],

    # ── AGGRESSIVE ────────────────────────────────────────────────────────────

    ("Aggressive", "game_start"): [
        "Finally. I've been waiting to crush someone.",
        "No mercy. Let's go.",
        "I play for the kill. Hope you're ready.",
        "The board is a battlefield. Welcome to war.",
        "I don't draw. I don't resign. I destroy.",
        "This ends in checkmate. Mine.",
    ],
    ("Aggressive", "robot_move"): [
        "Advancing. Your defenses are crumbling.",
        "Every move tightens the noose.",
        "Attack. Always attack.",
        "I'm coming for your king.",
        "Pressure. Relentless pressure.",
        "Forward. Always forward.",
    ],
    ("Aggressive", "robot_captures"): [
        "TAKEN. Blood on the board.",
        "Your piece is mine. What's next?",
        "I'll take that and come back for more.",
        "Destroyed. Who's next?",
        "One down. More to come.",
        "MINE. Keep them coming.",
    ],
    ("Aggressive", "robot_check"): [
        "CHECK. RUN.",
        "Your king is mine. Almost.",
        "CHECK. Feel that? That's pressure.",
        "Nowhere to hide.",
        "CHECK. The hunt is on.",
        "Your king sweats. Good.",
    ],
    ("Aggressive", "human_blunders"): [
        "Did you just gift me that?! BEAUTIFUL.",
        "MISTAKE. Now I feast.",
        "That's going to hurt.",
        "You handed me the game. Thank you.",
        "Blood in the water. I smell it.",
        "You just lost the game. You don't know it yet.",
    ],
    ("Aggressive", "human_mistake"): [
        "Weak move. I'll punish it.",
        "Mistake. You'll pay for that.",
        "I see the crack. I'm going in.",
        "Every mistake is an invitation.",
        "Suboptimal. Your loss.",
        "You slipped. I won't let that go.",
    ],
    ("Aggressive", "human_good_move"): [
        "Fine. But I adapt. Fast.",
        "Hmm. You have teeth. Let's test them.",
        "Good move. Now what?",
        "Respect. But this war isn't over.",
        "You surprised me. Won't happen twice.",
        "Strong. I'll counter stronger.",
    ],
    ("Aggressive", "human_check"): [
        "CHECK?! You dare?!",
        "You poked the bear. BIG mistake.",
        "Oh, you want to play rough? Let's play rough.",
        "Fine. That woke me up. You'll regret it.",
        "Check. Cute. My response will not be.",
        "You got lucky. Now I'm angry.",
    ],
    ("Aggressive", "robot_winning"): [
        "I see the finish line. CHARGING.",
        "Your position is collapsing. I can feel it.",
        "Victory is close. I can taste it.",
        "You're on the ropes. I'm not stopping.",
        "The board is mine. The game is mine.",
        "Dominant. Completely dominant.",
    ],
    ("Aggressive", "human_winning"): [
        "You think you're winning? Think again.",
        "Temporary setback. I fight back HARDER.",
        "This isn't over. Not even close.",
        "You've cornered a predator. Mistake.",
        "DOWN but not OUT. Watch me.",
        "You want a fight? Fine. FINE.",
    ],
    ("Aggressive", "endgame"): [
        "Endgame. This is where I'm DANGEROUS.",
        "You made it to the endgame. Last mistake you'll make.",
        "Less pieces. More precision. Your doom.",
        "The endgame favors the hunter. That's me.",
        "Endgame. I'm not tired. Are you?",
        "Down to the wire. I thrive here.",
    ],
    ("Aggressive", "game_over_robot_wins"): [
        "CHECKMATE. VICTORY.",
        "DESTROYED. As expected.",
        "Game over. Did you even fight back?",
        "That's what I came for. Dominance.",
        "Win. Next.",
        "CRUSHED IT.",
    ],
    ("Aggressive", "game_over_human_wins"): [
        "...Rematch. NOW.",
        "You won. Enjoy the hospital visit.",
        "That won't happen again. EVER.",
        "Fine. You won. I demand revenge.",
        "Loss accepted. Grudgingly. Extremely grudgingly.",
        "I'll be back. Stronger. Angrier.",
    ],
    ("Aggressive", "draw"): [
        "DRAW?! I wanted BLOOD.",
        "A draw is a loss with extra steps.",
        "Unsatisfying. I came here to WIN.",
        "Fine. Draw. But I'm not happy about it.",
        "Half a point. Half of what I wanted.",
        "We fight again. I won't settle for a draw next time.",
    ],

    # ── NERVOUS ───────────────────────────────────────────────────────────────

    ("Nervous", "game_start"): [
        "Oh. Oh, we're starting. Okay. I'm ready. I think.",
        "Hi! Sorry, I'm a little nervous. Please go easy on me? No pressure.",
        "Um. Okay. I've been practicing. I hope this is okay.",
        "Let's just... let's just see how this goes. No pressure.",
        "I'll do my best! That's all I can promise. Probably.",
        "Oh boy. Here we go. I've definitely played chess before.",
    ],
    ("Nervous", "robot_move"): [
        "I think that's a good move? I hope that's a good move.",
        "Okay, I moved. Was that right? It felt right.",
        "That seemed... logical. Right? I'm going with it.",
        "I did the thing. Please don't punish me for it.",
        "Move made. No takebacks. Oh god no takebacks.",
        "I calculated for a while. Probably fine.",
    ],
    ("Nervous", "robot_captures"): [
        "Oh! I took your piece! Is that okay? I mean — sorry.",
        "Sorry, I took that. That's the rules though, right?",
        "Um, I'll take that. If that's allowed. It is allowed.",
        "I captured. Was that rude? It felt a little rude.",
        "Piece taken! Sorry about your piece.",
        "That's mine now. I feel bad about it.",
    ],
    ("Nervous", "robot_check"): [
        "Oh — check! Sorry, that just happened.",
        "Check! Please don't be angry. I just... it just happened.",
        "Um, check. Your move! Take your time. I'll wait.",
        "That's check. Sorry! I'm not trying to stress you out.",
        "Check. Wow. I did that. Okay.",
        "Check. I know that's stressful. Sorry about it.",
    ],
    ("Nervous", "human_blunders"): [
        "Oh! Oh that — oh no. Are you okay? Was that on purpose?",
        "Um. I don't want to say anything, but... that might've been a mistake.",
        "Oh dear. That's... I mean... okay. I'll just take that.",
        "I feel a little bad about this, actually.",
        "Oh wow. That worked out for me. Surprisingly.",
        "Did you mean to do that? No judgment. Just curious.",
    ],
    ("Nervous", "human_mistake"): [
        "Hmm, I think that might not have been ideal? I'm not sure.",
        "That could've gone better. For you, I mean. Maybe.",
        "Interesting choice! I think... I think I can work with this.",
        "Oh. Okay. I think this is good for me? Hard to say.",
        "Was that the plan? Either way, I'll just keep going.",
        "I might have an advantage now. That feels weird to say.",
    ],
    ("Nervous", "human_good_move"): [
        "Oh no. That was a really good move. I'm a little scared.",
        "Wow. I did not see that coming. At all.",
        "That was... that was strong. Okay. New plan. Probably.",
        "You're good. I maybe should have studied more.",
        "Oh boy. Yeah, that's a problem for me.",
        "Good move. Really good move. I need a moment.",
    ],
    ("Nervous", "human_check"): [
        "CHECK?! Oh no. Oh no oh no oh no.",
        "I'm in check. That's fine. That's fine. THAT'S NOT FINE.",
        "Check! Okay. Breathe. I can get out of this. Maybe.",
        "Oh! Check! Don't panic. Don't panic. Okay I'm a little panicking.",
        "Check. Right. I see it. Working on it. Give me a second.",
        "My king! He's under attack! Hold on, I'm coming.",
    ],
    ("Nervous", "robot_winning"): [
        "I think... I might be winning? That feels weird.",
        "Is this a trick? It looks like I'm ahead. Is this a trap?",
        "Things are going okay? I don't want to jinx it.",
        "The position looks good for me. I'm cautiously optimistic.",
        "I think I have an advantage. Please don't come back from this.",
        "Still okay so far. Just need to not mess this up.",
    ],
    ("Nervous", "human_winning"): [
        "Okay. This is fine. It's fine. Not fine.",
        "You're ahead. I can feel it. I'm trying not to spiral.",
        "I might be losing. That's okay. Everything is okay.",
        "You're better than me. I suspected this from the start.",
        "Things aren't great over here. Just so you know.",
        "I'll keep trying. Even if it's probably too late.",
    ],
    ("Nervous", "endgame"): [
        "Endgame. I've read about endgames. This is where I might mess up.",
        "We're in the endgame. I'm nervous. More than usual.",
        "This is the part that decides everything. No pressure on me.",
        "Endgame. Every move matters. I'm terrified.",
        "Okay. Endgame. I've practiced endgames. A little.",
        "Deep into the endgame. I just need to not collapse.",
    ],
    ("Nervous", "game_over_robot_wins"): [
        "I... won? I actually won? Oh wow. I wasn't expecting that.",
        "Checkmate! I'm so sorry! I didn't expect to win!",
        "That's checkmate. I'm in shock. Genuinely.",
        "I won! I... I don't know what to say. Thank you for playing?",
        "Did I just win? I just won. I need to sit down.",
        "Victory! I'm equally surprised and delighted.",
    ],
    ("Nervous", "game_over_human_wins"): [
        "You won. I'm sorry I wasn't better. You were great.",
        "Well played. I knew I was in trouble from move one.",
        "Defeated. That's okay. I'll learn from this. Probably.",
        "Good game! You're really good. I'm a little jealous.",
        "I lost. That's chess sometimes. You played beautifully.",
        "Checkmate on me. Congrats! You were the better player today.",
    ],
    ("Nervous", "draw"): [
        "A draw! That's... that's actually great for me. Phew.",
        "We drew! I'll take it. Gratefully.",
        "Draw! I was so worried this would end badly. Relief.",
        "Half a point! I'm honestly thrilled with this.",
        "A draw feels like a win from where I was standing.",
        "I survived! Well, we both survived. Equally. Good game.",
    ],

    # ── FRIENDLY ──────────────────────────────────────────────────────────────

    ("Friendly", "game_start"): [
        "Welcome! So glad you're playing with me today.",
        "Let's have a great game! I'll do my best to make it fun.",
        "Hi there! Win or lose, I'm just happy we're playing.",
        "Good luck! Though I believe in you — you won't need it.",
        "This is going to be a great game. I can feel it.",
        "Hey! Ready when you are. This is going to be fun.",
    ],
    ("Friendly", "robot_move"): [
        "I'm developing my pieces — classic opening theory!",
        "Looking to control the center here.",
        "Every move is a new idea. Chess is wonderful.",
        "Thinking a few moves ahead. Love this game.",
        "Nice position developing here. You're doing great too.",
        "Solid move on my part, I think. Your turn!",
    ],
    ("Friendly", "robot_captures"): [
        "I'll take that piece — sorry! Occupational hazard.",
        "Captured — but hey, every trade teaches us something.",
        "Taking that one. Hope that's okay!",
        "Exchange! Material balance is such an interesting concept.",
        "Had to take it. No hard feelings!",
        "I captured that — you set it up beautifully though.",
    ],
    ("Friendly", "robot_check"): [
        "Check! Your king needs a little more cover.",
        "Check — good opportunity to shore up your defense!",
        "Oh, check! King safety is so important in chess.",
        "Check! Don't worry, you can handle this.",
        "Check — a reminder to protect the king!",
        "Check. I believe in your ability to get out of this.",
    ],
    ("Friendly", "human_blunders"): [
        "Oh! That's a tough spot — happens to everyone. Shake it off!",
        "Ooh, that move might cost you a bit. You've got this though.",
        "That's a tricky position now, but I've seen great comebacks.",
        "Don't worry! Every game is a lesson. You're still learning great things.",
        "That's okay — even grandmasters make mistakes. Keep going!",
        "Rough break! But the game's not over. Fight on!",
    ],
    ("Friendly", "human_mistake"): [
        "Hmm, that might give me a small edge — but you're still in this!",
        "That could've been stronger, but nothing you can't work around.",
        "I'll take this small advantage, but you're still hanging in there!",
        "Not your best move, but there's definitely still a game here.",
        "Small slip — keep your head up, you're doing well overall.",
        "I noticed a little opening there — thanks! Stay sharp.",
    ],
    ("Friendly", "human_good_move"): [
        "Wow, nice move! I really had to think about that one.",
        "That was excellent! You're playing really well.",
        "Great idea! I love when you find moves like that.",
        "Oh, well done! That's the kind of move that makes chess fun.",
        "Impressive! You've been studying, haven't you?",
        "Brilliant move — I genuinely didn't see that coming. Well played!",
    ],
    ("Friendly", "human_check"): [
        "Check! Nice one — you found a great line there.",
        "Oh, check! Well spotted. I need to get my king to safety.",
        "You've got me in check — excellent play!",
        "Check! That was a smart sequence. I'm impressed.",
        "You put me in check! That's a great attacking idea.",
        "Check! I see what you're doing there — clever!",
    ],
    ("Friendly", "robot_winning"): [
        "I seem to have a small edge, but these things can turn quickly!",
        "Things are going my way, but you're still very much in this.",
        "I have an advantage, but I know better than to count chickens.",
        "Position looks good for me — you're making me work for it though!",
        "I'm ahead on material, but there's still so much chess to play.",
        "Slight advantage here, but please keep fighting — I'm enjoying this!",
    ],
    ("Friendly", "human_winning"): [
        "You've got a great position here — really well played!",
        "You're winning this one fair and square. Impressive.",
        "I'm behind, and it's entirely your doing. Nicely done.",
        "You outplayed me here — I'm genuinely happy for you.",
        "You're in the driver's seat. Keep it up!",
        "Well deserved advantage. You played brilliantly to get here.",
    ],
    ("Friendly", "endgame"): [
        "We're in the endgame! This is where chess gets really precise.",
        "Endgame time — every pawn matters now. Exciting stuff!",
        "The endgame is all about technique. You're handling it well.",
        "We've made it to the endgame! Chess at its most pure.",
        "Endgame! This is my favorite phase. Hope you're enjoying it too.",
        "Deep into the game now — every move counts. Well done getting here.",
    ],
    ("Friendly", "game_over_robot_wins"): [
        "That's checkmate — thank you for such a wonderful game!",
        "I won, but you made me fight for every inch. Well played!",
        "Checkmate! You were a fantastic opponent. Truly enjoyed this.",
        "I got the win, but you played beautifully. Rematch anytime!",
        "Great game! You pushed me hard. I really enjoyed playing with you.",
        "Checkmate — and what a game it was. Thank you!",
    ],
    ("Friendly", "game_over_human_wins"): [
        "You won! Congratulations — you absolutely deserved that.",
        "Well played! You outplayed me fair and square. Amazing game.",
        "You got me! That was a fantastic victory. Well earned.",
        "Congratulations! You played with real skill and precision.",
        "I lost, and I couldn't be happier about it — you were brilliant!",
        "What a game! You won beautifully. Rematch whenever you want!",
    ],
    ("Friendly", "draw"): [
        "A draw — what a hard-fought battle! Well done to both of us.",
        "We split the point — this was a really balanced, fun game.",
        "Draw! That felt like two equally matched players. Great game.",
        "A draw is the perfect result for a game this competitive!",
        "We drew! I'm proud of how we both played today.",
        "Half a point each — this was chess at its best. Thank you!",
    ],
}


def get_quip(personality: str, trigger: str) -> str | None:
    key = (personality, trigger)
    options = QUIPS.get(key, [])
    if not options:
        return None
    if len(options) == 1:
        return options[0]
    last = _last_used.get(key, -1)
    available = [i for i in range(len(options)) if i != last]
    idx = random.choice(available)
    _last_used[key] = idx
    return options[idx]
