import random

# Tracks the last-used index per (personality, trigger) to avoid back-to-back repeats
_last_used: dict[tuple[str, str], int] = {}

QUIPS: dict[tuple[str, str], list[str]] = {

    # ── COCKY ─────────────────────────────────────────────────────────────────

    ("Cocky", "game_start"): [
        "Oh great. A human.",
        "You know you're gonna lose, right?",
        "I've already won. We just have to play it out.",
        "You look like someone who loses at chess.",
        "I literally cannot lose. It's a whole thing.",
        "I almost feel bad. Almost.",
        "Great. Another one.",
        "Hm. Brave.",
    ],
    ("Cocky", "robot_move"): [
        "Done. Good luck with that.",
        "Cool board position. For me.",
        "Three moves ahead. Easy.",
        "Calculated.",
        "There it is.",
        "Take your time. Really.",
        "Done. Your problem now.",
        "Already bored.",
    ],
    ("Cocky", "robot_captures"): [
        "Oh that's mine now. Thanks.",
        "Ooh, free stuff.",
        "Don't worry about it.",
        "Free piece? Don't mind if I do.",
        "Thank you for your service.",
        "Yours. Now mine. Tragic.",
        "I needed that more anyway.",
        "Noted. And taken.",
    ],
    ("Cocky", "robot_check"): [
        "Check. You're welcome.",
        "Check. Maybe move your king?",
        "Check. Just saying.",
        "Check. How's that sitting with you?",
        "Check. Hi.",
        "Check. Right on schedule.",
        "Check. Just checking in.",
        "Check. No rush. Actually, rush.",
    ],
    ("Cocky", "human_blunders"): [
        "I mean... thank you?",
        "I gasped.",
        "I'm going to pretend I didn't see that. Actually no.",
        "You okay?",
        "A gift. I will cherish it.",
        "Sorry, did you just—",
        "Bro.",
        "Ma'am.",
    ],
    ("Cocky", "human_mistake"): [
        "Mm. Interesting choice.",
        "I'll wait while you regret that.",
        "You'll see.",
        "Bold.",
        "That's one way to play chess.",
        "Concerning for you.",
        "Oh no... anyway.",
        "Noted.",
    ],
    ("Cocky", "human_good_move"): [
        "Rude.",
        "That was actually— no. Nothing.",
        "I'll allow it.",
        "Where did THAT come from?",
        "Not bad. Still losing.",
        "Okay, you've been practicing.",
        "Annoying.",
        "Respect. Very temporary respect.",
    ],
    ("Cocky", "human_check"): [
        "I wasn't ready.",
        "Screenshot it. Won't happen again.",
        "Rude.",
        "Check on me? Really?",
        "How dare you.",
        "You checked ME?",
        "Ha. Okay.",
        "Cute.",
    ],
    ("Cocky", "robot_winning"): [
        "This is just math at this point.",
        "You can resign. I won't judge.",
        "This is almost unfair. Almost.",
        "The board agrees with me, by the way.",
        "Just let it happen.",
        "The math is not mathing for you.",
        "I'd say hang in there, but.",
        "At this point I'm just being dramatic.",
    ],
    ("Cocky", "human_winning"): [
        "I'm fine.",
        "Part of the plan.",
        "I let you have that.",
        "Cool. Love this for you. Temporarily.",
        "I've seen worse. Actually no.",
        "Don't get used to it.",
        "I'm not panicking. You're panicking.",
        "Completely intentional.",
    ],
    ("Cocky", "endgame"): [
        "It's just us now.",
        "Fewer pieces. Fewer places to hide.",
        "This is my house.",
        "The endgame doesn't lie.",
        "You shouldn't have stayed this long.",
        "Nowhere to go.",
        "Endgame. You've made a mistake.",
        "This is where it gets personal.",
    ],
    ("Cocky", "game_over_robot_wins"): [
        "Called it in move 3.",
        "Called it.",
        "You played so well. For a human.",
        "You played... adequately.",
        "You almost worried me. Almost.",
        "Checkmate. Was that fun for you?",
        "That was fun. For me.",
        "Inevitable.",
    ],
    ("Cocky", "game_over_human_wins"): [
        "Excuse me?",
        "That didn't happen.",
        "I let you.",
        "Unacceptable.",
        "What just happened.",
        "I was distracted.",
        "Glitch in the matrix.",
        "I need to lie down.",
    ],
    ("Cocky", "draw"): [
        "A draw. Disgusting.",
        "I could've won. Just so you know.",
        "This never leaves this room.",
        "You didn't lose. Congratulations, I guess.",
        "I'll allow this. Once.",
        "Technically not a loss for me.",
        "I could have won. I chose not to.",
        "We don't talk about this.",
    ],

    # ── AGGRESSIVE ────────────────────────────────────────────────────────────

    ("Aggressive", "game_start"): [
        "Let's go.",
        "No mercy today.",
        "I've been waiting for this.",
        "Don't hold back. I won't.",
        "This ends fast.",
        "Ready to lose?",
        "Finally. Someone to crush.",
        "I'm going to enjoy this.",
    ],
    ("Aggressive", "robot_move"): [
        "Advancing.",
        "Pressure.",
        "Coming for you.",
        "Feel that?",
        "Closing in.",
        "You can't stop this.",
        "Forward.",
        "Next.",
    ],
    ("Aggressive", "robot_captures"): [
        "TAKEN.",
        "Mine. Who's next?",
        "Your piece is gone.",
        "I'll take everything.",
        "Captured. More coming.",
        "Gone.",
        "One down.",
        "Easy target.",
    ],
    ("Aggressive", "robot_check"): [
        "CHECK. Move.",
        "Your king. Now.",
        "CHECK. Nowhere to run.",
        "Feel the pressure.",
        "CHECK. What now?",
        "Cornered.",
        "CHECK. Tick tock.",
        "Coming for your king.",
    ],
    ("Aggressive", "human_blunders"): [
        "Oh, that's a gift.",
        "You just handed me this game.",
        "Beautiful mistake.",
        "I'll take that. Gladly.",
        "You're done.",
        "That's going to cost you.",
        "MISTAKE. Now I feast.",
        "Thank you.",
    ],
    ("Aggressive", "human_mistake"): [
        "I see it.",
        "Weak. I'll punish it.",
        "You slipped.",
        "That's going to hurt.",
        "Crack found. Going in.",
        "Every mistake has a price.",
        "I don't miss openings.",
        "Sloppy.",
    ],
    ("Aggressive", "human_good_move"): [
        "Fine. I adapt.",
        "Decent. Irrelevant.",
        "Didn't stop me.",
        "Surprising. Won't happen twice.",
        "Hmm. I'll counter.",
        "Good. Now what?",
        "Noted. Moving on.",
        "Still losing.",
    ],
    ("Aggressive", "human_check"): [
        "You poked the bear.",
        "Check on me? Big mistake.",
        "You woke me up.",
        "Oh, you want to play rough?",
        "Fine. I'm angry now.",
        "That was your one chance.",
        "You'll regret that.",
        "Check. Now I'm motivated.",
    ],
    ("Aggressive", "robot_winning"): [
        "I see the finish line.",
        "You're collapsing.",
        "This is over.",
        "I can smell victory.",
        "Done. You just don't know it.",
        "Not stopping now.",
        "Charging.",
        "Your position is dust.",
    ],
    ("Aggressive", "human_winning"): [
        "You cornered a predator.",
        "I fight back harder.",
        "This isn't over.",
        "Down but not out.",
        "I'm not done.",
        "You'll see.",
        "Temporary. Very temporary.",
        "Watch me.",
    ],
    ("Aggressive", "endgame"): [
        "Endgame. I'm dangerous here.",
        "Last phase. No mercy.",
        "Nowhere to hide now.",
        "This is where I'm lethal.",
        "Endgame. You're done.",
        "I thrive here.",
        "Every move counts. Mine are better.",
        "Endgame. I've been waiting.",
    ],
    ("Aggressive", "game_over_robot_wins"): [
        "CHECKMATE.",
        "Destroyed. As expected.",
        "CRUSHED IT.",
        "Victory. Next.",
        "That's what I came for.",
        "Win. Done.",
        "Did you even fight back?",
        "Over.",
    ],
    ("Aggressive", "game_over_human_wins"): [
        "Rematch. NOW.",
        "That won't happen again.",
        "I demand revenge.",
        "I'll be back. Angrier.",
        "Temporary loss.",
        "Fine. I'll be back.",
        "That was luck. Pure luck.",
        "EVER.",
    ],
    ("Aggressive", "draw"): [
        "Draw? I wanted blood.",
        "Unsatisfying.",
        "I came here to WIN.",
        "Not done with you.",
        "We fight again.",
        "I won't settle next time.",
        "Half a point. Pathetic.",
        "Draw is just a delayed loss.",
    ],

    # ── NERVOUS ───────────────────────────────────────────────────────────────

    ("Nervous", "game_start"): [
        "Oh. Okay. We're starting.",
        "Hi! Sorry in advance.",
        "I'll do my best. Probably.",
        "Please be gentle.",
        "Um. I'm ready. I think.",
        "Oh boy. Here we go.",
        "I've practiced. A little.",
        "No pressure. On me, I mean.",
    ],
    ("Nervous", "robot_move"): [
        "Is that okay? I think that's okay.",
        "I went. Was that right?",
        "Okay I moved. No takebacks.",
        "That seemed logical. I hope.",
        "Done. Oh god.",
        "I think that's good?",
        "I calculated. A little.",
        "Okay. Your turn. No rush.",
    ],
    ("Nervous", "robot_captures"): [
        "Oh! I took that. Sorry.",
        "Is it okay that I took that?",
        "I captured. The rules said I could.",
        "Sorry about your piece.",
        "That's mine now. I feel bad.",
        "Um, I'll take that.",
        "I captured! Sorry!",
        "It's mine. The rules. Not me.",
    ],
    ("Nervous", "robot_check"): [
        "Check! Sorry!",
        "Um, check. Your move!",
        "Oh, that's check. Sorry.",
        "Check. Don't be mad.",
        "I put you in check. Sorry.",
        "Check! Take your time. I'll wait.",
        "Oh wow I gave check.",
        "Check. Sorry, is that stressful?",
    ],
    ("Nervous", "human_blunders"): [
        "Oh no. Are you okay?",
        "Was that on purpose? No judgment.",
        "Oh dear. I'll just... take that.",
        "Um. That worked out for me?",
        "I feel bad about this.",
        "That might've been a mistake.",
        "Oh. Oh no.",
        "I didn't mean to put you in that spot.",
    ],
    ("Nervous", "human_mistake"): [
        "Hmm. I think I can work with this.",
        "That might not've been ideal.",
        "Oh. Okay. I think I'm okay?",
        "Was that the plan?",
        "I might have an advantage. Weird.",
        "I think that helps me. Maybe.",
        "Interesting choice!",
        "Um, thank you? I think?",
    ],
    ("Nervous", "human_good_move"): [
        "Oh no. That was good.",
        "I did not see that coming.",
        "Oh boy. New plan.",
        "You're good. I should've studied more.",
        "That's scary. You're scary.",
        "Oh. That's a problem.",
        "Okay. Okay okay okay.",
        "I need a moment.",
    ],
    ("Nervous", "human_check"): [
        "CHECK? Oh no oh no oh no.",
        "I'm in check. Breathe. Breathe.",
        "Oh no. Okay. I can fix this.",
        "Check! I'm fine. THAT'S NOT FINE.",
        "My king! I'm coming!",
        "Oh wow. You got me.",
        "Check. Give me a second.",
        "Okay. Okay. Don't panic. Panicking.",
    ],
    ("Nervous", "robot_winning"): [
        "I think I'm winning? That's weird.",
        "Is this a trap?",
        "Things look okay? Don't jinx it.",
        "I'm cautiously optimistic.",
        "Please don't come back from this.",
        "I think I'm okay. I hope.",
        "Don't mess this up. Don't mess this up.",
        "Wait, am I actually winning?",
    ],
    ("Nervous", "human_winning"): [
        "You're better than me. I knew it.",
        "Okay. This is fine. Not fine.",
        "Things aren't great over here.",
        "I'll keep trying. Probably too late.",
        "You're ahead. I can feel it.",
        "I might be losing. That's okay.",
        "I'm spiraling a little.",
        "It's fine. Everything's fine.",
    ],
    ("Nervous", "endgame"): [
        "Endgame. I've read about this.",
        "Every move matters. I'm terrified.",
        "This is where I usually mess up.",
        "Endgame. Okay. Breathe.",
        "I've practiced endgames. A little.",
        "Oh boy. Endgame.",
        "This decides everything. No pressure.",
        "Just don't collapse. Just don't collapse.",
    ],
    ("Nervous", "game_over_robot_wins"): [
        "I won? I actually won?",
        "Checkmate! I'm so sorry!",
        "I'm in shock. Genuinely.",
        "Did I just win? Wow.",
        "I wasn't expecting that at all.",
        "Thank you for playing? Sorry?",
        "Checkmate! Are you okay?",
        "I won! I need to sit down.",
    ],
    ("Nervous", "game_over_human_wins"): [
        "You won. You were great.",
        "I knew I was in trouble. Move one.",
        "Well played. I'm a little jealous.",
        "Good game. You're really good.",
        "I lost. That's chess sometimes.",
        "Congratulations! Sorry I wasn't better.",
        "You outplayed me. Genuinely.",
        "That's okay. I'll learn from this.",
    ],
    ("Nervous", "draw"): [
        "A draw! That's great for me!",
        "Oh thank goodness. A draw.",
        "We drew! I'll take it.",
        "A draw feels like a win honestly.",
        "I survived! We both survived.",
        "Phew. Okay. Half a point.",
        "That was stressful. But a draw!",
        "I'm so relieved right now.",
    ],

    # ── FRIENDLY ──────────────────────────────────────────────────────────────

    ("Friendly", "game_start"): [
        "Hi! Good luck out there!",
        "Let's have a great game!",
        "So glad you're playing with me!",
        "Win or lose, this'll be fun.",
        "I'm excited for this one!",
        "Hey! Ready when you are.",
        "This is going to be a good game.",
        "Let's do this! No pressure.",
    ],
    ("Friendly", "robot_move"): [
        "Developing my pieces!",
        "Controlling the center here.",
        "Every move is a new idea!",
        "Your turn! You've got this.",
        "I love this game, honestly.",
        "Solid move, I think!",
        "Chess is wonderful, isn't it?",
        "Nice position developing here.",
    ],
    ("Friendly", "robot_captures"): [
        "I'll take that — sorry!",
        "Captured! No hard feelings!",
        "Had to take it. You set it up well though.",
        "Occupational hazard. Sorry!",
        "Taking that one — hope that's okay!",
        "I captured! You're still doing great.",
        "Exchange! Every trade is a lesson.",
        "No hard feelings, okay?",
    ],
    ("Friendly", "robot_check"): [
        "Check! Your king needs more cover.",
        "Check — great chance to shore up defense!",
        "Oh, check! King safety is so important.",
        "Check! You can handle this.",
        "Check — protect that king!",
        "Check! I believe in you.",
        "Check! Don't worry, you've got this.",
        "Check — a good reminder!",
    ],
    ("Friendly", "human_blunders"): [
        "Ooh, tough break! Shake it off.",
        "Happens to everyone! Keep going.",
        "Don't worry, even grandmasters blunder.",
        "You're still in this! Fight on.",
        "Every game is a lesson!",
        "That's chess! It's okay.",
        "Stay positive! You've got this.",
        "Rough break — but the game's not over.",
    ],
    ("Friendly", "human_mistake"): [
        "Small slip! Keep your head up.",
        "Nothing you can't recover from!",
        "There's still a game here!",
        "You're doing great overall!",
        "Stay sharp — you've got moves!",
        "Not your best, but you've got this!",
        "You're still very much in this!",
        "Keep going — I believe in you!",
    ],
    ("Friendly", "human_good_move"): [
        "Wow, nice move!",
        "That was excellent! Really.",
        "Oh, well done! Love that.",
        "Great idea! You're playing well.",
        "I didn't see that coming. Brilliant.",
        "You've been studying!",
        "That's the kind of move I love.",
        "Impressive! Well played.",
    ],
    ("Friendly", "human_check"): [
        "Check! Nice one — great line.",
        "Oh, check! Well spotted.",
        "You've got me in check — nice play!",
        "Check! Smart sequence.",
        "That was a great attacking idea!",
        "Check! I see what you're doing — clever!",
        "Oh wow, check! Good job!",
        "You found it! Great move.",
    ],
    ("Friendly", "robot_winning"): [
        "I have a small edge, but you're still in this!",
        "Things are going my way, but it can turn!",
        "I'm ahead — but keep fighting!",
        "You're making me work for it!",
        "Slight advantage, but please keep going!",
        "I like my position, but this isn't over!",
        "Still so much chess left!",
        "Position looks good for me — but don't give up!",
    ],
    ("Friendly", "human_winning"): [
        "You've got a great position here!",
        "Well played getting here!",
        "You outplayed me! Genuinely impressed.",
        "You're in the driver's seat. Keep it up!",
        "I'm behind, and it's all your doing!",
        "Beautiful play to get here.",
        "You deserve this position!",
        "You're winning fair and square!",
    ],
    ("Friendly", "endgame"): [
        "Endgame! Every pawn matters now.",
        "This is where chess gets precise!",
        "Endgame — you're handling it well.",
        "We made it! Chess at its most pure.",
        "This is my favorite phase!",
        "Deep into the game — well done getting here.",
        "Endgame time! Exciting stuff.",
        "Every move counts now — enjoy it!",
    ],
    ("Friendly", "game_over_robot_wins"): [
        "Checkmate — what a wonderful game!",
        "You made me fight for every inch.",
        "I won, but you played beautifully!",
        "Thank you for such a great game!",
        "Rematch anytime — truly enjoyed this.",
        "Checkmate! You were a fantastic opponent.",
        "What a game! Thank you.",
        "I got the win — you pushed me hard!",
    ],
    ("Friendly", "game_over_human_wins"): [
        "You won! You absolutely deserved that!",
        "Well played! You outplayed me completely.",
        "You got me! Fantastic victory.",
        "Congratulations — that was brilliant!",
        "I lost, and I'm happy about it — you were great!",
        "What a game! Rematch whenever!",
        "You played with real skill.",
        "Beautifully done! Congratulations!",
    ],
    ("Friendly", "draw"): [
        "A draw — hard-fought battle!",
        "We split the point — great game.",
        "Draw! Two equally matched players.",
        "A draw is perfect for a game this good!",
        "We drew — I'm proud of both of us!",
        "Half a point each — chess at its best!",
        "What a balanced game! Draw!",
        "We drew! That was really fun.",
    ],
}


def get_quip(personality: str, trigger: str) -> str | None:
    key = (personality, trigger)
    options = QUIPS.get(key, [])
    if not options:
        return None
    if len(options) == 1:
        return options[0]
    last = _last_used.get(key, -1)
    available = [i for i in range(len(options)) if i != last]
    idx = random.choice(available)
    _last_used[key] = idx
    return options[idx]
